services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: boobies
      POSTGRES_USER: dbuser
      POSTGRES_DB: uwuso
    volumes:
      - 'db:/var/lib/postgresql/data'
      - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 64M

  mongo:
    image: mongo:5.0.2
    restart: unless-stopped
    ports:
      - $MONGO_EXPOSE_PORT:$MONGO_PORT
    volumes:
      - db:/data/db
    env_file:
      - ./.env

  web:
    depends_on:
      - postgres
      - mongo
    image: boobspics-web
    ports:
      - $HTTP_EXPOSE_PORT:$HTTP_PORT
    volumes:
      - ./:/usr/src/boobspics
    container_name: boobspics-web
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - HTTP_PORT=$HTTP_PORT
      - MONGO_HOST=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGDATABASE=uwuso
      - LOG_WEBHOOK=$LOG_WEBHOOK
      - SHORTENER_URI=$SHORTENER_URI
    build: .

volumes:
  db:
