services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: boobies
      POSTGRES_USER: dbuser
      PGUSER: dbuser
      POSTGRES_DB: uwuso
    volumes:
      - 'pdb:/var/lib/postgresql/data'
      - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 64M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      start_period: 30s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdb:/data

  # TO REMOVE
  mongo:
    image: mongo:5.0.2
    restart: unless-stopped
    ports:
      - $MONGO_EXPOSE_PORT:$MONGO_PORT
    volumes:
      - db:/data/db
    env_file:
      - ./.env

  web:
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      mongo:
        condition: service_started
        restart: true
      redis-cache:
        condition: service_started
        restart: true
#    image: nekopavel/imagination-server:latest   #Uncomment this if you want to use prebuilt image
    ports:
      - $HTTP_EXPOSE_PORT:$HTTP_PORT
    volumes:
      - ./:/usr/src/boobspics
      - uploads:/usr/src/boobspics/privateuploads
    container_name: boobspics-web
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - HTTP_PORT=$HTTP_PORT
      - MONGO_HOST=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGDATABASE=uwuso
      - REDISHOST=$REDIS_HOST
      - LOG_WEBHOOK=$LOG_WEBHOOK
      - SHORTENER_URI=$SHORTENER_URI
    build: .                                      #Comment this line if using prebuilt image

volumes:
  db:
  pdb:
  redisdb:
  uploads:
